### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by SeanHayes** [epeli/source-map-peek#2]
```
$ node -v
v6.2.0
$ npm -v
3.8.9
```

```
$ npm install source-map-peek

> kexec@1.3.0 install /Users/sean/dev/web/node_modules/kexec
> node-gyp configure build

  CXX(target) Release/obj.target/kexec/src/kexec.o
../src/kexec.cc:22:30: error: use of undeclared identifier 'F_GETFD'
    int flags = fcntl (desc, F_GETFD, 0);
                             ^
../src/kexec.cc:26:15: error: use of undeclared identifier 'FD_CLOEXEC'
    flags &= ~FD_CLOEXEC; //clear FD_CLOEXEC bit
              ^
../src/kexec.cc:27:25: error: use of undeclared identifier 'F_SETFD'
    return fcntl (desc, F_SETFD, flags);
                        ^
3 errors generated.
make: *** [Release/obj.target/kexec/src/kexec.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/sean/dev/web/node_modules/kexec
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
tenor-web@1.0.0 /Users/sean/dev/web
└── (empty)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "install" "source-map-peek"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! kexec@1.3.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kexec@1.3.0 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kexec package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kexec
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kexec
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sean/dev/web/npm-debug.log
npm ERR! code 1

```

**Comment by wtfrank** [comment]
I also get this issue:
```

$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cat /etc/issue.net 
Ubuntu 16.04.4 LTS

```
